spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webshop
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#security:
#  oauth2:
#    client:
#      client-id: oauth2_client
#      client-secret: oauth2_client_secret
#    resource:
#      token-info-uri: http://localhost:8081/auth/oauth/check_token
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG



#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8081/auth/user


#server:
#  port: 8082
#  context-path: /resource
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testoauth2
#    username: root
#    password: 123456
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#security:
#  oauth2:
#    client:
#      client-id: oauth2_client
#      client-secret: oauth2_client_secret
#    resource:
#      token-info-uri: http://localhost:8081/authserver/oauth/check_token
#logging:
#  level:
#    org.springframework.security: DEBUG